### ISSUE TITLE
fork

### ISSUE THREAD

**Issue by GonzRon** [burnsfisher/hubitat-integration-skill#2] opened 2022-09-27 18:25 UTC
Hi There,

I forked the project and made some updates that might prove useful for first time users.
Namely, the plugin won't crash on an initial install, and won't throw exceptions prior to being configured.

Also there was an unreachable return statement that is now gone.

I've also added the appId param since the maker API app ID integer can change on hubitat installations.

my fork is GonzRon, I won't submit a pull request because the structure has changed, but wanted to make you aware of it!

Thank you kindly for writing this!!

**Comment by burnsfisher** [comment] 2022-09-30 20:31
Thanks for the fixes!  I'll take a look (at some point) and most likely incorporate your fixes!

**Comment by burnsfisher** [comment] 2022-09-30 20:41
Kind of a pain that the app ID number changes!  I had no idea.  Thanks for catching it!  And of course by the time I put in all the settings code, I already had it in my account!

**Comment by burnsfisher** [comment] 2022-12-29 22:01
I've checked this branch out in my PiCroft and it seems mostly ok after a small bit of playing.  I'll run it for a while before merging.

One problem:  When you added the app ID and I checked out the new branch I got a random number there, and nothing worked right (at least partly because the device database was empty).  This should probably be fixed (and maybe to token as well) to indicate something verbally to tell the user to fix the settings.  The issue is detecting it, I guess.

And one question...any particular reason you renamed the skill LCS Hubitat Integration?  What does LCS mean?

Thanks for all the work!  I've ordered a Mark II and at some point, I'll update this skill to work on it.  Have to find a way to work on both PiCroft and Mycroft MkII I guess.

**Comment by burnsfisher** [comment] 2022-12-30 21:56
Good work and thanks as I said before.  I did add a test for the two possible (that I could find) errors that return if you don't correctly specify an API number or a token.  It's all now merged into the main branch.

**Closed as completed by burnsfisher** 2022-12-30 21:56 UTC

**Comment by GonzRon** [comment] 2022-12-31 01:09
> One problem: When you added the app ID and I checked out the new branch I got a random number there, and nothing worked right (at least partly because the device database was empty). This should probably be fixed (and maybe to token as well) to indicate something verbally to tell the user to fix the settings. The issue is detecting it, I guess.
> 
Interesting, I hadn't noticed this issue.

> And one question...any particular reason you renamed the skill LCS Hubitat Integration? What does LCS mean?

Just some initials, I needed a way to test my updates and deploy from github without mixing up your original.

> Thanks for all the work! I've ordered a Mark II and at some point, I'll update this skill to work on it. Have to find a way to work on both PiCroft and Mycroft MkII I guess.

likewise, Mark II should be great to play with.

**Comment by GonzRon** [comment] 2022-12-31 01:10
> Good work and thanks as I said before. I did add a test for the two possible (that I could find) errors that return if you don't correctly specify an API number or a token. It's all now merged into the main branch.

thank you kindly, and happy to contribute, I never got back around to working on the more modular codebase I wrote about earlier, but I suspect as time goes on and the need arises, I'll be happy to contribute more.  Happy holidays!
